objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Component_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Component Attributes</relationshipLabel>
        <relationshipName>Component_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Component Attribute</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Component Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ComponentService.cls
//Service class.
public with sharing class ComponentService {
	
	public static List<ApexPages.Component> generate(Set<Id> componentIds) {
		List<Component__c> components = new List<Component__c>();
		components = [Select Id, Name, Order__c, Page__c, (Select Id, Name, Value__c, Key__c, Type__c from Component_Attributes__r)
					  from Component__c where Id in :componentIds order by Order__c];

		List<ApexPages.Component> dynamicComponents = new List<ApexPages.Component>();

		// This is where the magic happens.
		// Make sure that Apex class that implements the Interface matches with the Component Name.
		for (Component__c cmp : components) {
			IAvailableForVisualforce inst = (IAvailableForVisualforce) Type.forName(cmp.Name).newInstance();
			ComponentSettings settings = new ComponentSettings(cmp,cmp.Component_Attributes__r);
			dynamicComponents.add(inst.getComponent(settings));
		}

		return dynamicComponents;			  
	}

}