objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DynamicPageCon.cls
// Controller for Dynamic Page
public with sharing class DynamicPageCon {


	private Set<Id> componentIds;
	
	public DynamicPageCon() {
		
		componentIds = new Set<Id>();
		String pageId = ApexPages.currentPage().getParameters().get('id');

		for (Component__c cmp : [Select Id from Component__c where Page__c = :pageId and Is_Active__c = true order by Order__c])
			componentIds.add(cmp.Id);
	}

	public Component.Apex.OutputPanel getComponents() {
		Component.Apex.OutputPanel thePanel = new Component.Apex.OutputPanel();
		for (ApexPages.Component comp : ComponentService.generate(componentIds)) {
			Component.Apex.OutputPanel innerPanel = new Component.Apex.OutputPanel();
			innerPanel.childComponents.add(comp);
			innerPanel.layout = 'block';
			thePanel.childComponents.add(innerPanel);
		}
		return thePanel;
	}

}